// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SquirrelPublisher
{
    internal sealed partial class Vsix
    {
        public const string Id = "SquirrelPublisher.fc89d230-ecce-4c50-b0dc-3c3c637f41f8";
        public const string Name = "SquirrelPublisher";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Grigor Yeghiazaryan";
        public const string Tags = "";
    }
}
