// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SquirrelPublisher
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSquirrelPublisherPackageString = "1acf61a3-93c8-4a7e-89e8-44eca25d76e4";
        public static Guid guidSquirrelPublisherPackage = new Guid(guidSquirrelPublisherPackageString);

        public const string guidSquirrelPublisherPackageCmdSetString = "ec5a7cb8-667f-43ca-86c3-b27484bfc14c";
        public static Guid guidSquirrelPublisherPackageCmdSet = new Guid(guidSquirrelPublisherPackageCmdSetString);

        public const string guidImagesString = "0643f672-cfd1-4b4c-b450-62bc2d1bf2ee";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int InstallPackageId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}